HISTFILESIZE=20000
HISTSIZE=2000
HISTIGNORE=""
HISTCONTROL=""
readonly HISTFILE
readonly HISTCMD
readonly HISTSIZE
readonly HISTFILESIZE
readonly HISTIGNORE
readonly HISTCONTROL
PROMPT_COMMAND="${PROMPT_COMMAND:-:} ; history -a"
export HISTSIZE HISTFILESIZE HISTIGNORE HISTCONTROL PROMPT_COMMAND
export HISTTIMEFORMAT="$LOGNAME %F %T "
